# Generated by Django 4.1.5 on 2023-10-10 14:58

from django.db import migrations, models
import django.db.models.deletion
import video_creator.models.reddit_post


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.SlugField()),
                ('uid', models.SlugField()),
                ('text', models.TextField()),
                ('screenshot', models.ImageField(blank=True, upload_to=video_creator.models.reddit_post.get_upload_path)),
                ('audio', models.FileField(blank=True, upload_to=video_creator.models.reddit_post.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='StockVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RedditPostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video_creator.redditpost')),
                ('stock_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video_creator.stockvideo')),
            ],
        ),
        migrations.CreateModel(
            name='RedditComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField()),
                ('text', models.TextField()),
                ('screenshot', models.ImageField(blank=True, upload_to=video_creator.models.reddit_post.get_upload_path)),
                ('audio', models.FileField(blank=True, upload_to=video_creator.models.reddit_post.get_upload_path)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='video_creator.redditpost')),
            ],
        ),
    ]
