# Generated by Django 4.1.5 on 2023-10-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
