# Generated by Django 4.1.5 on 2023-10-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_creator', '0003_redditcomment_url_stockvideo_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='video_creator.redditpost'),
        ),
    ]
