# Generated by Django 4.1.5 on 2023-10-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_creator', '0005_redditcomment_embed_code_redditpost_embed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditcomment',
            name='embed_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditcomment',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='embed_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
